
SELECT ins.ANIMAL_ID
  , ins.NAME 
FROM ANIMAL_INS AS ins
INNER JOIN ANIMAL_OUTS outs ON outs.ANIMAL_ID = ins.ANIMAL_ID
WHERE ins.ANIMAL_ID = outs.ANIMAL_ID 
ORDER BY outs.DATETIME - ins.DATETIME DESC
LIMIT 2