SELECT user.USER_ID
  , user.NICKNAME
  , CONCAT(user.CITY, ' ', user.STREET_ADDRESS1, ' ', user.STREET_ADDRESS2) AS 전체주소
  , CONCAT(SUBSTRING(user.TLNO, 1, 3), '-', SUBSTRING(user.TLNO, 4, 4), '-', SUBSTRING(user.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER user
INNER JOIN USED_GOODS_BOARD board ON user.USER_ID = board.WRITER_ID
GROUP BY user.USER_ID
HAVING COUNT(board.WRITER_ID) >= 3
ORDER BY user.USER_ID DESC