SELECT COUNT(info.FISH_TYPE) AS FISH_COUNT
  , nameInfo.FISH_NAME AS FISH_NAME
FROM FISH_INFO info
LEFT JOIN FISH_NAME_INFO nameInfo ON nameInfo.FISH_TYPE = info.FISH_TYPE
GROUP BY nameInfo.FISH_NAME
ORDER BY FISH_COUNT DESC