SELECT book.CATEGORY
, SUM(bookSales.SALES) AS TOTAL_SALES
FROM BOOK book
LEFT JOIN BOOK_SALES bookSales ON book.BOOK_ID = bookSales.BOOK_ID
WHERE bookSales.SALES_DATE LIKE '2022-01%'
GROUP BY book.CATEGORY
ORDER BY book.CATEGORY ASC;